### ISSUE TITLE
Stray "S" included in breaking changes if commit message is spelled "BREAKING CHANGES"

### ISSUE THREAD

**Issue by jeffbcross** [conventional-changelog/conventional-changelog-core#14]
See this commit message: https://github.com/angular/angular/commit/098b461

Notice it says "BREAKING CHANGE**S**:" with an S at the end.

If I generate a changelog with `preset: angular, releaseCount: 1` including that commit, the breaking change ends up having an "S" after the scope, like so:

```
* core: S:

Previously multiple template bindings on one element
(ex. `<div *ngIf='..' *ngFor='...'>`) were allowed but most of the time
were leading to undesired result. It is possible that a small number
of applications will see template parse errors that shuld be fixed by
nesting elements or using `<template>` tags explicitly.
```

A lot of commit messages add the S at the end of breaking changes, so I think it would be worthwhile to add a special case for that. Happy to open a PR if this sounds reasonable :).

Dependency versions:
 * gulp-conventional-changelog 1.1.0 
 * conventional-changelog 1.1.0 
 * conventional-changelog-core 1.5.0

**Comment by Tapppi** [comment]
PR for such a case would be appreciated!
