### ISSUE TITLE
flow issue

### ISSUE THREAD

**Issue by oliviertassinari** [conventional-changelog/conventional-changelog-core#23]
I have the following error when running `flow@0.38.0`:
> $ flow
node_modules/conventional-changelog-core/test/fixtures/_malformation.json:1
  1:
     ^ Unexpected end of input

I fixed it by adding the following lines in my `.flowconfig` file:
```
[ignore]
.*/node_modules/conventional-changelog-core/.*\.json$
```

**Would it makes sense to remove the tests files from the package?**

**Comment by stevemao** [comment]
see https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/22
