### ISSUE TITLE
issuePrefixes Parser Option No Longer Respected

### ISSUE THREAD

**Issue by destroyerofbuilds** [conventional-changelog/conventional-changelog-core#6]
I use a package similar to [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog-angular) with a single major difference.

Inside the `parserOpts` object (https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/index.js#L18) I set `issuePrefixes` to `['#', '@']`. However, only the `#` prefix is respected by `conventional-commits-parser`.

It seems [this line](https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/merge-config.js#L222) is replacing my `issuePrefixes` value with the default for my SCM system (as retrieved from [here](https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/merge-config.js#L183)).

If I comment out that line, my prefix is respected, and my changelog is generated correctly.

**Comment by destroyerofbuilds** [comment]
An update:

At one point our custom `issuePrefixes` worked as desired. It seems the regression happened after the release of `get-pkg-repo` version 1.2. Our custom prefix worked when we were using version 1.0.0 of `get-pkg-repo`.

On line 131 the following is called:

```
repo = getPkgRepo(pkg)
```

Using version 1.0.0 of `get-pkg-repo` we get an empty repo object.

Therefore our custom prefixes are used, because `core` doesn't know what SCM provider defaults to use.

Using version 1.2.0 of `get-pkg-repo` we get something like the following:

```
repo { domain: '<REDACTED>',
  user: 'example-group',
  project: 'example-project' }
```

This causes `core` to load the defaults for our SCM, and then use those defaults instead of our custom prefixes.

**Comment by stevemao** [comment]
PR welcome.

**Comment by destroyerofbuilds** [comment]
@stevemao, sounds good. I'll take a look at it as soon as I have an opportunity.
