### ISSUE TITLE
No more commit hash links in changelog since version 1.3.3

### ISSUE THREAD

**Issue by vankeer** [conventional-changelog/conventional-changelog-core#7]
Since version 1.3.3 is released our changelog task does not generate any commit links anymore.

My guess is that the change in lib/merge-config.js in commit eaa3b6f1b1672362e2ab343ce33ce95cb43fe11c breaks it when calling the changelog task without a context object (and within a git repo).

`repo.browse()` will never be called because `context.host` is filled in through calling `getPkgRepo(pkg)` which calls `git-remote-origin-url`

**Comment by stevemao** [comment]
A bit more details would be appreciated. Or even better, send a PR.

**Comment by vankeer** [comment]
Thanks for the response. Here's an example of what goes wrong in our case: https://github.com/vankeer/conventional-changelog/commit/2eb757356b6e3d7c22cc95c3fea8174b91b41fbb

Basically, our Git repo is hosted on a local Stash instance (see the package.json in the commit for an example of the URL). `get-pkg-repo` apparently can't extract the project from the URL, but it can get the domain. So if you look at the `lib/merge-config.js` code on line 143: context.host is defined, the rest isn't, so the repository URL isn't set to `browse`.

One possible fix (other than perhaps changing `get-pkg-repo`) would be reverting the change to `lib/merge-config.js` as I don't understand why `context.repository = context.repository || repo.project || browse;` was not ok, but I'm not aware of the context of the fix
